development:
  adapter: postgresql
  database: vacation_development
	username: <%= ENV['PG_USER'] %>
	password: <%= ENV['PG_PASS'] %>
	host: localhost

test:
  adapter: postgresql
  database: vacation_test
